apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sandox-daemonset
  namespace: default
  labels:
    app: sandox
spec:
  selector:
    matchLabels:
      name: sandox
  template:
    metadata:
      labels:
        name: sandox
    spec:
      containers:
      - name: sandox
        image: docker.io/sandbox:v1.0.0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
