kind: Deployment
apiVersion: apps/v1
metadata:
  name: sandbox-deployment
  namespace: default
  labels:
    app: sandbox
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sandbox
  strategy:
    type: RollingUpdate # options: RollingUpdate, Recreate (default to rolling update)
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: sandbox
    spec:
      containers:
        - name: sandbox
          image: sandbox:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 900Mi
            requests:
              cpu: 300m
              memory: 900Mi
          startupProbe:
            httpGet:
              path: /healthz
              port: 80
            failureThreshold: 1
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            failureThreshold: 1
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            failureThreshold: 1
            initialDelaySeconds: 3
            periodSeconds: 3
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - app
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: type
                operator: In
                values:
                - generic
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      securityContext: {}
      schedulerName: default-scheduler
