apiVersion: batch/v1
kind: Job
metadata:
  name: sandbox-job
spec:
  template:
    spec:
      containers:
      - name: sandbox
        image: docker.io/sandbox:v1.0.0
        command: ["python",  "script.py", "-user", "someuser"]
      restartPolicy: OnFailure # Possible values: "Always", "Never", "OnFailure"
  backoffLimit: 5 #Specifies the number of retries before marking this job failed. Defaults to 6

