apiVersion: v1
kind: Service
metadata:
  name: sandbox-load-balancer-svc
spec:
  type: LoadBalancer  # <- Defining type is necessary.!!
  selector:
    app: sandbox
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000