apiVersion: v1
kind: Service
metadata:
  name: sandbox-external-ip-svc
spec:
  selector:
    app: sandbox
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  externalIPs:
    - 8.9.10.11 # <- This is your external IP