apiVersion: v1
kind: Service
metadata:
  name: sandbox-headless-svc
spec:
  clusterIP: None # <- This must be None!!
  selector:
    app: sandbox
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000