apiVersion: v1
kind: Service
metadata:
  name: sandbox-multi-port-svc
spec:
  selector:
    app: sandbox
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8000