apiVersion: v1
kind: Service
metadata:
  name: sandbox-node-port-svc
spec:
  type: NodePort
  selector:
    app: sandbox
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007 # <- This is optional, by default kubernetes will allocate a port from a range (default: 30000-32767)